name: Terraform Actions

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dev-standard

    steps:
    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.3

    - name: Terraform Validate
      run: |
        terraform init -backend=false
        terraform validate

  plan:
    name: Terraform Plan
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/terraform-common.yml
    secrets: inherit

    steps:
    - name: Terraform Init & Plan
      run: |
        terraform init
        terraform plan -out=dev-tfplan

    - uses: actions/upload-artifact@v4
      with:
        name: dev-tfplan
        path: dev-standard/dev-tfplan

  apply:
    name: Terraform Apply
    needs: plan
    if: github.event_name == 'workflow_dispatch'
    environment: terraform-apply
    uses: ./.github/workflows/terraform-common.yml
    secrets: inherit

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: dev-tfplan
        path: dev-standard

    - name: Terraform Init & Apply
      run: |
        terraform init
        terraform apply -auto-approve dev-tfplan
