name: Terraform Actions

on:
  workflow_dispatch:
    inputs:
      run_apply:
        description: "Apply after successful plan?"
        required: true
        default: "false"
        type: choice
        options: ["false", "true"]

jobs:
  plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dev-standard

    steps:
    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.3

    - name: Init & Plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform init
        terraform plan -out=dev-tfplan

    - uses: actions/upload-artifact@v4
      with:
        name: dev-tfplan
        path: dev-standard/dev-tfplan

  apply:
    needs: plan
    if: github.event.inputs.run_apply == 'true'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dev-standard

    steps:
    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - uses: actions/download-artifact@v4
      with:
        name: dev-tfplan
        path: dev-standard

    - name: Init & Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform init
        terraform apply -auto-approve dev-tfplan
