name: Terraform Actions

on:
  push:
    branches:
      - master          # plan on merge (state compare)

  workflow_dispatch:    # manual apply

jobs:
  plan:
    name: Terraform Init & Plan (dev-standard)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dev-standard   # ⬅ THIS IS THE KEY

    steps:
    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init & Plan
      run: |
        pwd
        terraform workspace show
        terraform state list
        terraform init -reconfigure
        terraform plan -out=dev-tfplan

    - uses: actions/upload-artifact@v4
      with:
        name: dev-tfplan
        path: dev-standard/dev-tfplan

  apply:
    name: Terraform Apply (dev-standard)
    needs: plan
    runs-on: ubuntu-latest
    environment: terraform-apply   # ⬅ approval gate

    defaults:
      run:
        working-directory: dev-standard

    steps:
    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - uses: actions/download-artifact@v4
      with:
        name: dev-tfplan
        path: dev-standard

    - name: Terraform Apply
      run: |
        terraform init -reconfigure
        terraform apply -auto-approve dev-tfplan
